import Header from "../components/Header";
import HeroEngine from "../components/HeroEngine";
import Explorer from "../components/Explorer";
import ContactForm from "../components/ContactForm";
import JourneyAddButton from "../components/JourneyAddButton";
import HideChapterButton from "../components/HideChapterButton";
import { JourneyProvider } from "../components/JourneyContext";
import { LanguageProvider } from "../components/LanguageContext";
import { CurrencyProvider } from "../components/CurrencyContext";

const experiences=[
 {id:"signature:luanda-city",title:"Luanda City Welcome",meta:"4 hours · Culture",category:"Culture",days:.5,img:"/assets/highlight-luanda.jpg",text:"A private introduction to Angola’s capital, its history, bay, architecture and living culture."},
 {id:"signature:kissama",title:"Kissama Safari Day",meta:"Full day · Wildlife",category:"Wildlife",days:1,img:"/assets/highlight-kissama.jpg",text:"A guided escape into Angola’s natural landscapes with wildlife viewing and thoughtful local support."},
 {id:"signature:kalandula-malanje",title:"Kalandula Falls & Malanje",meta:"2 days · Nature",category:"Nature",days:2,img:"/assets/highlight-kalandula.jpg",text:"Feel the power of Kalandula and discover the striking landscapes of Pedras Negras."},
 {id:"signature:culture-dance",title:"Angolan Culture & Dance",meta:"Culture · Cuisine",category:"Culture",days:1,img:"/assets/highlight-culture.jpg",text:"Rhythm, heritage and hospitality brought together in an experience rooted in Angola."},
 {id:"signature:mussulo",title:"Mussulo Island Escape",meta:"Full day · Coast",category:"Coast",days:1,img:"/assets/mussulo-luxury-island-escape.png",text:"Calm water, fresh seafood and a slower rhythm only a short journey from Luanda."},
 {id:"signature:kwanza",title:"Kwanza River Journey",meta:"8 hours · Heritage",category:"Heritage",days:1,img:"/assets/kwanza-river-boat.png",text:"River tranquillity, cultural history and extraordinary viewpoints south of the capital."}
];
const world=["South Africa","Zanzibar","Morocco","Seychelles","Portugal","France","Italy","Greece","Dubai","Maldives","Bali","Thailand","Brazil","New York","Caribbean"];

export default function Page(){return <LanguageProvider><CurrencyProvider><JourneyProvider><><Header/><main>
 <HeroEngine/>
 <section id="angola" className="meet section-pad"><div className="meet-image"><img src="/assets/kalandula-falls.jfif" alt="Kalandula Falls in Angola"/></div><div className="meet-copy"><p className="eyebrow">Meet Angola</p><h2>Some places are visited.<br/><em>Others are discovered.</em></h2><p className="lead">Angola is a land of extraordinary contrasts—Atlantic coastlines, dramatic mountain passes, powerful waterfalls, wildlife and vibrant traditions.</p><p>Every region reveals another chapter of a country still wonderfully undiscovered. Imbondeiro Travel introduces it with local knowledge, careful planning and genuine hospitality.</p><a className="text-link dark" href="#explorer">Explore the living map <span>→</span></a></div></section>
 <Explorer/>
 <section id="experiences" className="section-pad experiences"><div className="section-intro"><p className="eyebrow">Experiences Worth Remembering</p><h2>Signature Angola journeys</h2><p>Thoughtfully curated beginnings for travellers seeking nature, culture, coast and connection. Add any journey to your personal collection and keep exploring.</p></div><div className="experience-grid">{experiences.map((x,i)=><article key={x.title}><div className="card-image"><img src={x.img} alt={x.title}/><span>{String(i+1).padStart(2,'0')}</span></div><p className="card-meta">{x.meta}</p><h3>{x.title}</h3><p>{x.text}</p><JourneyAddButton item={{...x,image:x.img,province:"Signature Angola Journey",kind:"tour"}} label="Add Tour to My Journey"/></article>)}</div></section>
 <section id="world" className="world section-pad menu-reveal-section" aria-hidden="true"><HideChapterButton/><div className="section-intro light"><p className="eyebrow">Beyond Angola</p><h2>The World Collection</h2><p>Handpicked destinations for honeymoons, family journeys, cultural escapes and extraordinary celebrations.</p></div><div className="world-grid">{world.map((x,i)=>{const item={id:`world:${x.toLowerCase().replaceAll(' ','-')}`,title:x,category:"Worldwide",province:"The World Collection",kind:"world",days:0,image:"/assets/hero-kalandula.jpg"};return <article key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>Curated journeys, selected stays and personalised planning.</p><JourneyAddButton item={item}/></article>})}</div></section>
 <section id="services" className="menu-only-chapters section-pad menu-reveal-section" aria-hidden="true"><HideChapterButton/><article><p className="eyebrow">Services</p><h2>Travel, thoughtfully coordinated.</h2><p>Private journeys, airport assistance, corporate travel, MICE support, transfers and destination management across Angola.</p></article><article id="journal"><p className="eyebrow">Imbondeiro Journal</p><h2>Stories before the journey.</h2><p>Editorial destination notes, cultural insight and inspiration from Angola and the world.</p></article><article id="partners"><p className="eyebrow">DMC & Partners</p><h2>Your trusted ground partner in Angola.</h2><p>Professional logistics and curated programmes for tour operators, institutions and international partners.</p></article></section>
 <section id="about" className="about section-pad menu-reveal-section" aria-hidden="true"><HideChapterButton/><div><p className="eyebrow">The People Behind the Journey</p><h2>Rooted in Angola.<br/><em>Connected to the world.</em></h2></div><div><p className="lead">Imbondeiro Travel is a destination management and travel company creating meaningful journeys across Angola and carefully selected destinations worldwide.</p><div className="pillars"><article><h3>Mission</h3><p>To design meaningful journeys through exceptional service, local expertise and genuine hospitality.</p></article><article><h3>Vision</h3><p>To become Africa’s most trusted gateway to authentic travel experiences.</p></article><article><h3>Values</h3><p>Authenticity · Hospitality · Excellence · Discovery · Responsibility · Partnership</p></article></div></div></section>
 <section id="contact" className="contact section-pad"><div className="contact-copy"><p className="eyebrow">Begin Your Journey</p><h2>Where will your lifetime experience begin?</h2><p>When your collection feels right, click <strong>Craft My Journey</strong> in the Explorer. Your selections will arrive here ready for a personalised consultation.</p><p className="contact-direct">imbondeirotravel@gmail.com</p></div><ContactForm/></section>
 </main><footer><img src="/assets/imbondeiro-logo-luxury-web.png" alt="Imbondeiro Travel"/><p>Your Lifetime Experience Starts Here.</p><p>Project Baobab · Crafted with passion for Angola and the world.</p></footer></></JourneyProvider></CurrencyProvider></LanguageProvider>}
