"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";

const LanguageContext=createContext(null);
const STORAGE="imbondeiro-language-v1";

export const languages=[
 {code:"en",label:"English",short:"EN"},
 {code:"pt",label:"Português",short:"PT"},
 {code:"fr",label:"Français",short:"FR"},
 {code:"es",label:"Español",short:"ES"},
];

const copy={
 en:{meet:"Meet Angola",explorer:"The Imbondeiro Explorer",journey:"My Journey",menu:"Menu",close:"Close",gateway:"The Gateway to Angola",signature:"Signature Journeys",experiences:"Experiences",world:"Beyond Angola",services:"Services",journal:"Imbondeiro Journal",story:"Our Story",partners:"DMC & Partners",contact:"Contact",language:"Language",currency:"Currency",converter:"Currency converter",chapter:"Chapter One · The Gateway to Angola",headline1:"Your Lifetime",headline2:"Experience",headline3:"Starts Here",heroLede:"Private journeys across Angola and beyond, thoughtfully designed around you.",plan:"Plan Your Journey",discover:"Discover Angola",begin:"Begin your journey through Angola",whatCalls:"What calls you to Angola?",choose:"Choose an experience to explore the destinations that speak to you.",explore:"Explore",inAngola:"in Angola",selectReveal:"Select a destination, reveal its story, and add it to your journey.",selectedDestinations:"Your selected destinations",empty:"Your journey is empty",emptyHelp:"Start exploring and add destinations to begin.",keep:"Keep exploring",shape:"Your Journey Is Taking Shape",shapeHelp:"Add 3 or more destinations to shape your journey.",craft:"Craft My Journey",add:"Add to My Journey",remove:"Remove from My Journey",recommended:"Recommended stay",note:"Journey note",duration:"Estimated duration",travelStyle:"Travel style",nature:"Nature",culture:"Culture",wildlife:"Wildlife",coast:"Coast",romance:"Romance",heritage:"Heritage",menuIntro:"A quiet gateway to every chapter of Imbondeiro Travel.",selectedCurrency:"Preferred currency",convert:"Convert",amount:"Amount",from:"From",to:"To",rateError:"Live exchange rate is temporarily unavailable."},
 pt:{meet:"Conheça Angola",explorer:"O Explorador Imbondeiro",journey:"A Minha Viagem",menu:"Menu",close:"Fechar",gateway:"A Porta de Entrada para Angola",signature:"Viagens de Assinatura",experiences:"Experiências",world:"Além de Angola",services:"Serviços",journal:"Jornal Imbondeiro",story:"A Nossa História",partners:"DMC e Parceiros",contact:"Contacto",language:"Idioma",currency:"Moeda",converter:"Conversor de moeda",chapter:"Capítulo Um · A Porta de Entrada para Angola",headline1:"A Experiência",headline2:"da Sua Vida",headline3:"Começa Aqui",heroLede:"Viagens privadas por Angola e pelo mundo, cuidadosamente desenhadas à sua medida.",plan:"Planear a Sua Viagem",discover:"Descobrir Angola",begin:"Comece a sua viagem por Angola",whatCalls:"O que o chama a Angola?",choose:"Escolha uma experiência e descubra os destinos que falam consigo.",explore:"Explore",inAngola:"em Angola",selectReveal:"Selecione um destino, descubra a sua história e adicione-o à sua viagem.",selectedDestinations:"Os seus destinos selecionados",empty:"A sua viagem está vazia",emptyHelp:"Comece a explorar e adicione destinos.",keep:"Continue a explorar",shape:"A Sua Viagem Está a Ganhar Forma",shapeHelp:"Adicione 3 ou mais destinos para criar a sua viagem.",craft:"Criar a Minha Viagem",add:"Adicionar à Minha Viagem",remove:"Remover da Minha Viagem",recommended:"Estadia recomendada",note:"Nota de viagem",duration:"Duração estimada",travelStyle:"Estilo de viagem",nature:"Natureza",culture:"Cultura",wildlife:"Vida Selvagem",coast:"Costa",romance:"Romance",heritage:"Património",menuIntro:"Uma entrada tranquila para cada capítulo da Imbondeiro Travel.",selectedCurrency:"Moeda preferida",convert:"Converter",amount:"Montante",from:"De",to:"Para",rateError:"A taxa de câmbio em tempo real está temporariamente indisponível."},
 fr:{meet:"Découvrir l’Angola",explorer:"L’Explorateur Imbondeiro",journey:"Mon Voyage",menu:"Menu",close:"Fermer",gateway:"La Porte de l’Angola",signature:"Voyages Signature",experiences:"Expériences",world:"Au-delà de l’Angola",services:"Services",journal:"Journal Imbondeiro",story:"Notre Histoire",partners:"DMC et Partenaires",contact:"Contact",language:"Langue",currency:"Devise",converter:"Convertisseur de devises",chapter:"Chapitre Un · La Porte de l’Angola",headline1:"L’Expérience",headline2:"de Toute une Vie",headline3:"Commence Ici",heroLede:"Des voyages privés en Angola et ailleurs, conçus avec soin autour de vous.",plan:"Planifier Votre Voyage",discover:"Découvrir l’Angola",begin:"Commencez votre voyage en Angola",whatCalls:"Qu’est-ce qui vous appelle en Angola ?",choose:"Choisissez une expérience et explorez les destinations qui vous parlent.",explore:"Explorez",inAngola:"en Angola",selectReveal:"Sélectionnez une destination, découvrez son histoire et ajoutez-la à votre voyage.",selectedDestinations:"Vos destinations sélectionnées",empty:"Votre voyage est vide",emptyHelp:"Commencez à explorer et ajoutez des destinations.",keep:"Continuez à explorer",shape:"Votre Voyage Prend Forme",shapeHelp:"Ajoutez 3 destinations ou plus pour façonner votre voyage.",craft:"Créer Mon Voyage",add:"Ajouter à Mon Voyage",remove:"Retirer de Mon Voyage",recommended:"Séjour recommandé",note:"Note de voyage",duration:"Durée estimée",travelStyle:"Style de voyage",nature:"Nature",culture:"Culture",wildlife:"Faune",coast:"Côte",romance:"Romance",heritage:"Patrimoine",menuIntro:"Une porte discrète vers chaque chapitre d’Imbondeiro Travel.",selectedCurrency:"Devise préférée",convert:"Convertir",amount:"Montant",from:"De",to:"Vers",rateError:"Le taux de change en direct est temporairement indisponible."},
 es:{meet:"Conozca Angola",explorer:"El Explorador Imbondeiro",journey:"Mi Viaje",menu:"Menú",close:"Cerrar",gateway:"La Puerta de Angola",signature:"Viajes de Autor",experiences:"Experiencias",world:"Más Allá de Angola",services:"Servicios",journal:"Revista Imbondeiro",story:"Nuestra Historia",partners:"DMC y Socios",contact:"Contacto",language:"Idioma",currency:"Moneda",converter:"Conversor de moneda",chapter:"Capítulo Uno · La Puerta de Angola",headline1:"La Experiencia",headline2:"de Su Vida",headline3:"Comienza Aquí",heroLede:"Viajes privados por Angola y el mundo, diseñados cuidadosamente a su medida.",plan:"Planificar Su Viaje",discover:"Descubrir Angola",begin:"Comience su viaje por Angola",whatCalls:"¿Qué le llama de Angola?",choose:"Elija una experiencia y explore los destinos que conectan con usted.",explore:"Explore",inAngola:"en Angola",selectReveal:"Seleccione un destino, descubra su historia y añádalo a su viaje.",selectedDestinations:"Sus destinos seleccionados",empty:"Su viaje está vacío",emptyHelp:"Empiece a explorar y añada destinos.",keep:"Siga explorando",shape:"Su Viaje Está Tomando Forma",shapeHelp:"Añada 3 o más destinos para dar forma a su viaje.",craft:"Crear Mi Viaje",add:"Añadir a Mi Viaje",remove:"Quitar de Mi Viaje",recommended:"Estancia recomendada",note:"Nota de viaje",duration:"Duración estimada",travelStyle:"Estilo de viaje",nature:"Naturaleza",culture:"Cultura",wildlife:"Vida Salvaje",coast:"Costa",romance:"Romance",heritage:"Patrimonio",menuIntro:"Una puerta serena a cada capítulo de Imbondeiro Travel.",selectedCurrency:"Moneda preferida",convert:"Convertir",amount:"Cantidad",from:"De",to:"A",rateError:"El tipo de cambio en vivo no está disponible temporalmente."}
};

export function LanguageProvider({children}){
 const [language,setLanguage]=useState("en");
 useEffect(()=>{const saved=localStorage.getItem(STORAGE);if(copy[saved])setLanguage(saved)},[]);
 useEffect(()=>{localStorage.setItem(STORAGE,language);document.documentElement.lang=language},[language]);
 const value=useMemo(()=>({language,setLanguage,languages,t:(key)=>copy[language]?.[key]||copy.en[key]||key}),[language]);
 return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function useLanguage(){const v=useContext(LanguageContext);if(!v)throw new Error("useLanguage requires LanguageProvider");return v}
